//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class ImuMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Imu";
        public override string RosMessageName => k_RosMessageName;

        public float a_x;
        public float a_y;
        public float a_z;
        public float w_x;
        public float w_y;
        public float w_z;

        public ImuMsg()
        {
            this.a_x = 0.0f;
            this.a_y = 0.0f;
            this.a_z = 0.0f;
            this.w_x = 0.0f;
            this.w_y = 0.0f;
            this.w_z = 0.0f;
        }

        public ImuMsg(float a_x, float a_y, float a_z, float w_x, float w_y, float w_z)
        {
            this.a_x = a_x;
            this.a_y = a_y;
            this.a_z = a_z;
            this.w_x = w_x;
            this.w_y = w_y;
            this.w_z = w_z;
        }

        public static ImuMsg Deserialize(MessageDeserializer deserializer) => new ImuMsg(deserializer);

        private ImuMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.a_x);
            deserializer.Read(out this.a_y);
            deserializer.Read(out this.a_z);
            deserializer.Read(out this.w_x);
            deserializer.Read(out this.w_y);
            deserializer.Read(out this.w_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a_x);
            serializer.Write(this.a_y);
            serializer.Write(this.a_z);
            serializer.Write(this.w_x);
            serializer.Write(this.w_y);
            serializer.Write(this.w_z);
        }

        public override string ToString()
        {
            return "ImuMsg: " +
            "\na_x: " + a_x.ToString() +
            "\na_y: " + a_y.ToString() +
            "\na_z: " + a_z.ToString() +
            "\nw_x: " + w_x.ToString() +
            "\nw_y: " + w_y.ToString() +
            "\nw_z: " + w_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
