//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class SonarMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Sonar";
        public override string RosMessageName => k_RosMessageName;

        public float[] ranges;

        public SonarMsg()
        {
            this.ranges = new float[0];
        }

        public SonarMsg(float[] ranges)
        {
            this.ranges = ranges;
        }

        public static SonarMsg Deserialize(MessageDeserializer deserializer) => new SonarMsg(deserializer);

        private SonarMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
        }

        public override string ToString()
        {
            return "SonarMsg: " +
            "\nranges: " + System.String.Join(", ", ranges.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
