//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class ImuUnityMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/ImuUnity";
        public override string RosMessageName => k_RosMessageName;

        public float time;
        public float a_x;
        public float a_y;
        public float a_z;
        public float w_x;
        public float w_y;
        public float w_z;
        public float angle_z;

        public ImuUnityMsg()
        {
            this.time = 0.0f;
            this.a_x = 0.0f;
            this.a_y = 0.0f;
            this.a_z = 0.0f;
            this.w_x = 0.0f;
            this.w_y = 0.0f;
            this.w_z = 0.0f;
            this.angle_z = 0.0f;
        }

        public ImuUnityMsg(float time, float a_x, float a_y, float a_z, float w_x, float w_y, float w_z, float angle_z)
        {
            this.time = time;
            this.a_x = a_x;
            this.a_y = a_y;
            this.a_z = a_z;
            this.w_x = w_x;
            this.w_y = w_y;
            this.w_z = w_z;
            this.angle_z = angle_z;
        }

        public static ImuUnityMsg Deserialize(MessageDeserializer deserializer) => new ImuUnityMsg(deserializer);

        private ImuUnityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
            deserializer.Read(out this.a_x);
            deserializer.Read(out this.a_y);
            deserializer.Read(out this.a_z);
            deserializer.Read(out this.w_x);
            deserializer.Read(out this.w_y);
            deserializer.Read(out this.w_z);
            deserializer.Read(out this.angle_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
            serializer.Write(this.a_x);
            serializer.Write(this.a_y);
            serializer.Write(this.a_z);
            serializer.Write(this.w_x);
            serializer.Write(this.w_y);
            serializer.Write(this.w_z);
            serializer.Write(this.angle_z);
        }

        public override string ToString()
        {
            return "ImuUnityMsg: " +
            "\ntime: " + time.ToString() +
            "\na_x: " + a_x.ToString() +
            "\na_y: " + a_y.ToString() +
            "\na_z: " + a_z.ToString() +
            "\nw_x: " + w_x.ToString() +
            "\nw_y: " + w_y.ToString() +
            "\nw_z: " + w_z.ToString() +
            "\nangle_z: " + angle_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
