//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class MultiSonarUnityMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/MultiSonarUnity";
        public override string RosMessageName => k_RosMessageName;

        public float time;
        public float distance_front;
        public float distance_left;
        public float distance_right;

        public MultiSonarUnityMsg()
        {
            this.time = 0.0f;
            this.distance_front = 0.0f;
            this.distance_left = 0.0f;
            this.distance_right = 0.0f;
        }

        public MultiSonarUnityMsg(float time, float distance_front, float distance_left, float distance_right)
        {
            this.time = time;
            this.distance_front = distance_front;
            this.distance_left = distance_left;
            this.distance_right = distance_right;
        }

        public static MultiSonarUnityMsg Deserialize(MessageDeserializer deserializer) => new MultiSonarUnityMsg(deserializer);

        private MultiSonarUnityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
            deserializer.Read(out this.distance_front);
            deserializer.Read(out this.distance_left);
            deserializer.Read(out this.distance_right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
            serializer.Write(this.distance_front);
            serializer.Write(this.distance_left);
            serializer.Write(this.distance_right);
        }

        public override string ToString()
        {
            return "MultiSonarUnityMsg: " +
            "\ntime: " + time.ToString() +
            "\ndistance_front: " + distance_front.ToString() +
            "\ndistance_left: " + distance_left.ToString() +
            "\ndistance_right: " + distance_right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
