//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class PoseUnityMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/PoseUnity";
        public override string RosMessageName => k_RosMessageName;

        public float time;
        public float euler_x;
        public float euler_y;
        public float euler_z;
        public float position_x;
        public float position_y;
        public float position_z;

        public PoseUnityMsg()
        {
            this.time = 0.0f;
            this.euler_x = 0.0f;
            this.euler_y = 0.0f;
            this.euler_z = 0.0f;
            this.position_x = 0.0f;
            this.position_y = 0.0f;
            this.position_z = 0.0f;
        }

        public PoseUnityMsg(float time, float euler_x, float euler_y, float euler_z, float position_x, float position_y, float position_z)
        {
            this.time = time;
            this.euler_x = euler_x;
            this.euler_y = euler_y;
            this.euler_z = euler_z;
            this.position_x = position_x;
            this.position_y = position_y;
            this.position_z = position_z;
        }

        public static PoseUnityMsg Deserialize(MessageDeserializer deserializer) => new PoseUnityMsg(deserializer);

        private PoseUnityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
            deserializer.Read(out this.euler_x);
            deserializer.Read(out this.euler_y);
            deserializer.Read(out this.euler_z);
            deserializer.Read(out this.position_x);
            deserializer.Read(out this.position_y);
            deserializer.Read(out this.position_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
            serializer.Write(this.euler_x);
            serializer.Write(this.euler_y);
            serializer.Write(this.euler_z);
            serializer.Write(this.position_x);
            serializer.Write(this.position_y);
            serializer.Write(this.position_z);
        }

        public override string ToString()
        {
            return "PoseUnityMsg: " +
            "\ntime: " + time.ToString() +
            "\neuler_x: " + euler_x.ToString() +
            "\neuler_y: " + euler_y.ToString() +
            "\neuler_z: " + euler_z.ToString() +
            "\nposition_x: " + position_x.ToString() +
            "\nposition_y: " + position_y.ToString() +
            "\nposition_z: " + position_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
