//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class SonarUnityMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/SonarUnity";
        public override string RosMessageName => k_RosMessageName;

        public float time;
        public float distance;
        public int confidence;

        public SonarUnityMsg()
        {
            this.time = 0.0f;
            this.distance = 0.0f;
            this.confidence = 0;
        }

        public SonarUnityMsg(float time, float distance, int confidence)
        {
            this.time = time;
            this.distance = distance;
            this.confidence = confidence;
        }

        public static SonarUnityMsg Deserialize(MessageDeserializer deserializer) => new SonarUnityMsg(deserializer);

        private SonarUnityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time);
            deserializer.Read(out this.distance);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
            serializer.Write(this.distance);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "SonarUnityMsg: " +
            "\ntime: " + time.ToString() +
            "\ndistance: " + distance.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
